extends Node
class_name GolfCourseLayout

const LEVEL_LAYOUT := [
	["W", "W", "W", "W", "W", "W", "W", "W", "W", "W", "W", "W", "W", "W", "W", "W", "W", "W", "W", "W", "W", "W", "W", "W", "W", "W", "W", "W", "W", "W", "W", "W", "W", "W", "W", "W", "W", "W", "W", "W", "W", "W", "W", "W", "W", "W", "W", "W", "W", "W"],
	["Base", "Base", "Base", "Base", "Base", "T", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "T", "T", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base"],
	["Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "T", "T", "Base", "Base", "Base", "Base", "W", "W", "Base", "W", "W", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "W", "W", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "T"],
	["Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "W", "W", "Base", "W", "W", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "T", "Base", "Base", "W", "W", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base"],
	["Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "T", "Base", "Base", "Base", "Base", "Base", "Base", "T", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "T", "Base", "Base", "T", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "T", "G", "G", "G", "G", "Base", "Base", "Base"],
	["Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "T", "Base", "Base", "Base", "Base", "Base", "T", "Base", "Base", "T", "Base", "Base", "Base", "Base", "G", "G", "P", "G", "Base", "Base", "Base"],
	["Base", "Base", "SHOP", "Base", "Base", "T", "Base", "Base", "Base", "Base", "S", "S", "Base", "Base", "Base", "W", "W", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "G", "G", "G", "G", "Base", "Base", "Base"],
	["Base", "Base", "Base", "Base", "R", "R", "Base", "Base", "Base", "R", "S", "S", "R", "R", "R", "W", "W", "Base", "Base", "S", "S", "R", "R", "S", "S", "Base", "Base", "R", "Base", "Base", "R", "R", "Base", "Base", "R", "Base", "R", "Base", "Base", "Base", "S", "S", "S", "R", "Base", "Base", "Base", "Base", "Base", "Base"],
	["Base", "Base", "Base", "Base", "Base", "R", "R", "R", "R", "R", "R", "R", "R", "R", "R", "R", "R", "R", "R", "S", "S", "R", "R", "S", "S", "R", "R", "R", "R", "R", "R", "R", "R", "R", "R", "R", "R", "R", "R", "R", "S", "S", "S", "R", "Base", "Base", "Base", "Base", "Base", "Base"],
	["Base", "Base", "Base", "Base", "Base", "R", "R", "R", "R", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "R", "R", "R", "R", "Base", "Base", "Base", "T", "Base", "Base"],
	["Base", "Base", "Tee", "Tee", "Tee", "R", "R", "R", "S", "S", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "R", "R", "R", "Base", "Base", "Base", "Base", "Base", "Base"],
	["Base", "Base", "Tee", "Tee", "Tee", "R", "R", "F", "S", "S", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "R", "R", "Base", "Base", "Base", "Base", "Base", "Base"],
	["Base", "Base", "Tee", "Tee", "Tee", "R", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "R", "Base", "Base", "Base", "Base", "Base", "Base"],
	["Base", "Base", "Base", "Base", "Base", "R", "R", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "R", "R", "Base", "Base", "Base", "Base", "Base", "Base"],
	["Base", "Base", "Base", "Base", "R", "R", "R", "R", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "R", "R", "R", "Base", "Base", "Base", "Base", "Base", "Base"],
	["Base", "Base", "Base", "Base", "Base", "R", "R", "R", "R", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "R", "R", "R", "R", "R", "Base", "Base", "Base", "Base", "Base"],
	["Base", "Base", "Base", "Base", "Base", "R", "R", "R", "R", "R", "R", "R", "R", "R", "R", "R", "R", "R", "R", "R", "R", "R", "R", "R", "R", "R", "R", "R", "R", "R", "R", "S", "S", "R", "R", "R", "R", "R", "R", "R", "R", "R", "R", "R", "R", "Base", "Base", "Base", "Base", "Base"],
	["Base", "Base", "Base", "Base", "Base", "Base", "R", "Base", "R", "Base", "Base", "Base", "Base", "Base", "R", "R", "Base", "Base", "R", "Base", "Base", "R", "Base", "Base", "R", "Base", "Base", "R", "Base", "Base", "Base", "S", "S", "Base", "R", "Base", "Base", "Base", "Base", "R", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base"],
	["Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base"],
	["Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base"],
	["Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base"],
	["Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base", "Base"],
	["W", "W", "W", "W", "W", "W", "W", "W", "W", "W", "W", "W", "W", "W", "W", "W", "W", "W", "W", "W", "W", "W", "W", "W", "W", "W", "W", "W", "W", "W", "W", "W", "W", "W", "W", "W", "W", "W", "W", "W", "W", "W", "W", "W", "W", "W", "W", "W", "W", "W"],
]
